AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This template builds cron job for the private photo album

Parameters:
  S3Bucket:
    Type: String
  AUTHEMAIL:
    Type: String
  AUTHPWD:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Environment:
      Variables:
        S3Bucket: !Ref S3Bucket
        EMAIL: !Ref AUTHEMAIL
        PASSWORD: !Ref AUTHPWD

Resources:
  MediaDownloaderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: main.handler
      # Should have finished within 15min in my case
      # for longer needs: https://hands-on.cloud/aws-step-functions-long-running-tasks/#aws-lambda-long-running-tasks
      Timeout: 900
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
        - S3WritePolicy:
            BucketName: !Ref S3Bucket
      Events:
        ScheduledDownloader:
          Type: Schedule
          Properties:
            Name: MediaDownloaderSchedule
            Description: Cron job to download and upload media to photo album s3 bucket
            Schedule: "cron(0 22 ? * MON-FRI *)" # (minutes hours day_of_month month day_of_week year) default: UTC
            # ScheduleExpressionTimezone: "EST"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        External: 
          - 'aws-lambda'
        EntryPoints: 
        - src/main.ts
